spring:
  application:
    name: DH-CONNECTIVITY
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres 
    password: pine1234
    driver-class-name: org.postgresql.Driver

ingest:
  dataModelApiUrl: http://192.168.1.192:8083/datamodels
  interfaceApiUrl: http://192.168.1.192:8084/entityOperations/upsert?options=update
  interfaceApiUrlUseYn: Y
  daemonSrv: http://localhost:8888


server:
  timezone: Asia/Seoul 
  port: 18080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      

logging:
  level: 
    root: info
  config: classpath:config/log4j2.xml

# mybatis info
mybatis: 
  type-aliases-package: com.cityhub.web
  configuration:
    callSettersOnNulls: true
    

# auth info
cityhub:
  auth: 
    yn: N
    clientId: 48qfjmrLZpj8  
    clientSecret: imgVwgVXMJnDez11Tmp4  
    authorizationUri: http://119.195.143.33:30000/oauth2.0/authorize
    tokenUri: http://119.195.143.33:30000/oauth2.0/token
    publicKeyUri: http://119.195.143.33:30000/security/publickey
    logoutUri: http://119.195.143.33:30000/security/logout
    userInfoUri: http://119.195.143.33:30000/security/users
    redirectUri: http://222.107.32.38:18080/accesstoken

  
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://133.186.162.81:8888/eureka
