version: '3'
  
services:
  postgres:
    container_name: ingestdb
    image: postgis/postgis:11-2.5-alpine
    hostname: postgres
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DBNAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pine1234
    ports:
      - 5430:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    healthcheck:
      test: "exit 0"

  ingestdaemon:
    container_name: ingestdaemon
    image: pinecni/ingest-daemon:latest
    hostname: ingestdaemon
    ports:
      - 8888:8888
    volumes:
      -  log-data:/opt/logs  
    environment:
      - TZ=Asia/Seoul
      - DATAMODEL_API_URL=http://10.0.0.36:8080/datamodels
      - INGEST_INTERFACE_API_URL=http://10.0.0.25:8080/entityOperations/upsert?options=update
    depends_on:
      postgres:
        condition: service_healthy
        
  ingestweb:
    container_name: ingestweb
    image: pinecni/ingest-web:latest 
    hostname: ingestweb
    ports:
      - 8080:8080
    volumes:
      -  log-data:/opt/logs        
    environment:
      - TZ=Asia/Seoul
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - DATASOURCE_ID=postgres
      - DATASOURCE_PW=pine1234
      - DAEMON_URL=http://ingestdaemon:8888
      - DATAMODEL_API_URL=http://10.0.0.36:8080/datamodels
      - INGEST_INTERFACE_API_USE_YN=Y
      - INGEST_INTERFACE_API_URL=http://10.0.0.25:8080/entityOperations/upsert?options=update
      - AUTH_YN=N
      - AUTH_EXTERNAL_URL=http://203.253.128.181:30084
      - AUTH_INTERNAL_URL=http://10.0.0.237:30000
      - AUTH_CLIENT_ID=V43z0o2boLrXia0E5zn6
      - AUTH_CLIENT_SECRET=YikQaYqOaHvIvOpGt42lfGvxAiJ4DsYY
      - AUTH_REDIRECT_URL=http://203.253.128.181:9208
      - EUREKA_ENABLED=false
      - EUREKA_EUREKA_DEFAULT_ZONE=http://10.0.0.144:8888/eureka
    depends_on:
      postgres:
        condition: service_healthy
      ingestdaemon:
        condition: service_started

volumes:
  log-data:

