version: '3'
  
services:
  postgres:
    container_name: smartcitydb
    image: postgis/postgis:11-2.5-alpine
    hostname: postgres
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DBNAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pine1234
    ports:
      - 5430:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure

  ingest:
    container_name: smartcityingest
    image: pinecni/smartcity-daemon:latest
    hostname: smartcityingest
    ports:
      - 8888:8888    
    environment:
      - TZ=Asia/Seoul    
      - AGENT_NAME=agent1st
      - AGENT_FILE=./conf/agent1st.conf
      - AGENT_CONF=./conf
      - SCHEMA_URL=http://10.0.0.36:8080/datamodels
      - DATACORE_URL=http://10.0.0.25:8080/entityOperations/upsert?options=update

  web:
    container_name: smartcityweb
    image: pinecni/smartcity-web:latest 
    hostname: smartcityweb
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - DATASOURCE_ID=postgres
      - DATASOURCE_PW=pine1234
      - DAEMON_URL=http://smartcityingest:8888
      - SCHEMA_URL=http://10.0.0.36:8080/datamodels
      - DATACORE_URL=http://10.0.0.25:8080/entityOperations/upsert?options=update
      - GATEWAY_USE_YN=N
      - GATEWAY_URL=http://13.124.164.104:8080      
      - AUTH_YN=N
      - AUTH_USER_ID=cityhub03
      - AUTH_USER_PASWORD=cityhub03!
      - AUTH_EXTERNAL_URL=http://203.253.128.181:30084
      - AUTH_INTERNAL_URL=http://10.0.0.237:30000
      - AUTH_CLIENT_ID=V43z0o2boLrXia0E5zn6
      - AUTH_CLIENT_SECRET=YikQaYqOaHvIvOpGt42lfGvxAiJ4DsYY
      - AUTH_REDIRECT_URL=http://203.253.128.181:9208
      - EUREKA_ENABLED=false
      - EUREKA_EUREKA_DEFAULT_ZONE=http://10.0.0.144:8888/eureka
    depends_on:
      - postgres
      - ingest



