spring:
  profiles: dev
  application:
    name: DH-CONNECTIVITY-DAEMON
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_ID} 
    password: ${DATASOURCE_PW}    
  


logging:
  config: classpath:config/log4j2.xml
  level:
    root: info

server:
  timezone: ${TZ} 
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force: true

flume:
  home: /opt/flume
  conf: /opt/flume/conf/
  log: /opt/logs/

