spring:
  application:
    name: DH-CONNECTIVITY-DAEMON
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ingest-db:5432/postgres
    username: postgres 
    password: pine1234


logging:
  config: classpath:config/log4j2.xml
  level:
    root: info

server:
  timezone: Asia/Seoul 
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force: true
        
flume:
  home: /opt/flume
  conf: /opt/flume/conf/
  log: /opt/logs/
    